apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloud-based-sensor
  description: >-
    Infrastructure configuration to manage CCCS's Cloud Based Sensor in AWS
    accounts
  labels:
    license: MIT
spec:
  type: service
  lifecycle: production
  owner: group:cds-snc/internal-sre
  domain: site-reliability-engineering
