##################################################################################
#                                                                                 
#   Conformance Pack:                                                             
#     Canadian Centre for Cyber Security (CCCS) Cloud Based Sensor (CBS)                                
#                                                                                 
#   This conformance pack helps verify compliance with CBS requirements.   
#                                                                                 
#   See Parameters section for names and descriptions of required parameters.     
#                                                                                 
##################################################################################

Resources:
  CloudtrailEnabled:
    Properties:
      ConfigRuleName: cbs_cloudtrail_enabled
      Description: A Config rule that checks that CloudTrail is enabled and logging to a given bucket.
      InputParameters:
        s3BucketName: ${satellite_logging_bucket}
      Scope:
        ComplianceResourceTypes:
          - AWS::CloudTrail::Trail
      Source:
        Owner: AWS
        SourceIdentifier: CLOUD_TRAIL_ENABLED
    Type: AWS::Config::ConfigRule
  ElbLoggingEnabled:
    Properties:
      ConfigRuleName: cbs_elb_logging_enabled
      Description: Checks that the CBS satellite bucket exists in the account.
      Scope:
        ComplianceResourceTypes:
          - AWS::ElasticLoadBalancing::LoadBalancer
          - AWS::ElasticLoadBalancingV2::LoadBalancer
      Source:
        Owner: AWS
        SourceIdentifier: ELB_LOGGING_ENABLED
    Type: AWS::Config::ConfigRule
  S3BucketLoggingEnabled:
    Properties:
      ConfigRuleName: cbs_s3_bucket_logging_enabled
      Description: A Config rule that checks whether logging to the cbs satellite is enabled for your S3 buckets.
      InputParameters:
        targetBucket: ${satellite_logging_bucket}
      Scope:
        ComplianceResourceTypes:
          - AWS::S3::Bucket
      Source:
        Owner: CUSTOM_LAMBDA
        SourceDetails:
          - EventSource: aws.config
            MaximumExecutionFrequency: TwentyFour_Hours
            MessageType: ScheduledNotification
        SourceIdentifier: ${cbs_s3_access_logs_rule_lambda_arn}
    Type: AWS::Config::ConfigRule
  S3SatelliteBucket:
    Properties:
      ConfigRuleName: cbs_s3_satellite_bucket_rule
      Description: Checks that the CBS satellite bucket exists in the account.
      InputParameters:
        satelliteBucket: ${satellite_logging_bucket}
      Scope:
        ComplianceResourceTypes:
          - AWS::S3::Bucket
      Source:
        Owner: CUSTOM_LAMBDA
        SourceDetails:
          - EventSource: aws.config
            MaximumExecutionFrequency: TwentyFour_Hours
            MessageType: ScheduledNotification
        SourceIdentifier: ${cbs_s3_satellite_bucket_rule_lambda_arn}
    Type: AWS::Config::ConfigRule
  VpcFlowLogsEnabled:
    Properties:
      ConfigRuleName: cbs_vpc_flow_logging_enabled
      Description: A Config rule that checks whether VPC flow logs are enabled.
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::VPC
      Source:
        Owner: AWS
        SourceIdentifier: VPC_FLOW_LOGS_ENABLED
    Type: AWS::Config::ConfigRule
  WAFv2LoggingEnabled:
    Properties:
      ConfigRuleName: cbs_wafv2_logs_rule
      Description: Checks that the WAFV2 ACL's are logging to either S3 or Kinesis.
      Scope:
        ComplianceResourceTypes:
          - AWS::WAFv2::WebACL
      Source:
        Owner: CUSTOM_LAMBDA
        SourceDetails:
          - EventSource: aws.config
            MaximumExecutionFrequency: TwentyFour_Hours
            MessageType: ScheduledNotification
        SourceIdentifier: ${cbs_wafv2_logs_rule_lambda_arn}
    Type: AWS::Config::ConfigRule