# Config for checkov Terraform static analysis

skip-check:
  - CKV_AWS_35  # CloudTrail default service key encryption is acceptable
  - CKV_AWS_36  # CloudTrail log validation not required
  - CKV_AWS_115 # Lambda function-level concurrent execution limit not required
  - CKV_AWS_116 # Lambda dead-letter queue not required
  - CKV_AWS_117 # Lambda configured within a VPC not required
  - CKV_AWS_145 # S3 default service key encryption is acceptable
  - CKV_AWS_158 # CloudWatch default service key encryption is acceptable
  - CKV2_AWS_10 # CloudTrail integration with CloudWatch not required
