# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "this-is-the-song-that-never-ends-tf"
    dynamodb_table = "terraform-state-lock-dynamo"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "ca-central-1"
  }
}
