name: "Terragrunt plan central"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/terragrunt-plan-central.yml"
      - "satellite_accounts"
      - "terragrunt/aws/alarms/**"
      - "terragrunt/aws/central_account/**"
      - "terragrunt/env/central/**"
      - "terragrunt/env/common/**"
      - "terragrunt/env/terragrunt.hcl"

env:
  AWS_REGION: ca-central-1
  CONFTEST_VERSION: 0.27.0
  TERRAFORM_VERSION: 1.1.4
  TERRAGRUNT_VERSION: 0.36.0
  TF_INPUT: false
  TF_VAR_cbs_principal_arn: ${{ secrets.CBS_PRINCIPAL_ARN }}
  TF_VAR_slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_CBS }}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup terraform tools
        uses: cds-snc/terraform-tools-setup@cc15ce9039f6c37c592fb9930b70466b229d2e9b # tag=v1

      - uses: cds-snc/paths-filter@b316143212d841aed668b7b29240c719d603a9b9 # v2.10.4
        id: filter
        with:
          filters: |
            alarms:
              - 'terragrunt/aws/alarms/**'
              - 'terragrunt/env/central/alarms/**'
            central_account:
              - 'terragrunt/aws/central_account/**'
              - 'terragrunt/env/central/central_account/**'
            common:
              - '.github/workflows/terragrunt-plan-central.yml'
              - 'satellite_accounts'
              - 'terragrunt/env/common/**'
              - 'terragrunt/env/terragrunt.hcl'

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::871282759583:role/ConfigTerraformAdministratorRole
          role-session-name: CBSGitHubActions
          aws-region: "ca-central-1"

      - name: Terragrunt plan central account
        if: ${{ steps.filter.outputs.central_account == 'true' || steps.filter.outputs.common == 'true' }}
        uses: cds-snc/terraform-plan@b84f6e89f3e7b5ecf648a2c036c043c73d82da59 # v3.1.0
        with:
          directory: "terragrunt/env/central/central_account"
          comment-delete: "true"
          comment-title: "Central account"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan alarms
        if: ${{ steps.filter.outputs.alarms == 'true' || steps.filter.outputs.common == 'true' }}
        uses: cds-snc/terraform-plan@b84f6e89f3e7b5ecf648a2c036c043c73d82da59 # v3.1.0
        with:
          directory: "terragrunt/env/central/alarms"
          comment-delete: "true"
          comment-title: "Central Alarms"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"
