name: "Terraform security scan"

on:
  push:
    branches:
      - main
    paths:
      - "terragrunt/aws/**"
      - ".github/workflows/terraform-security-scan.yml"      
  pull_request:
    paths:
      - "terragrunt/aws/**"
      - ".github/workflows/terraform-security-scan.yml"

jobs:
  terraform-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2.4.2

      - name: Checkov security scan
        uses: bridgecrewio/checkov-action@8d1675bd19257514c72879a34c5dfe108d0d3028 # latest as of Jan 19, 2022
        with:
          directory: terragrunt/aws
          framework: terraform
          output_format: cli
          soft_fail: false