name: "Terragrunt plan core"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/terragrunt-plan-core.yml"
      - "terragrunt/aws/core_account/**"
      - "terragrunt/env/core/**"
      - "terragrunt/env/common/**"
      - "terragrunt/env/terragrunt.hcl"

env:
  AWS_REGION: ca-central-1
  CONFTEST_VERSION: 0.27.0
  TERRAFORM_VERSION: 1.1.4
  TERRAGRUNT_VERSION: 0.36.0
  TF_INPUT: false

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2.4.2

      - name: Setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - uses: cds-snc/paths-filter@87bb78bc509076907db04d7f616bd2533af0e7fe # tag=v2.10.3
        id: filter
        with:
          filters: |
            core_account:
              - 'terragrunt/aws/core_account/**'
              - 'terragrunt/env/core_account/**'
            common:
              - '.github/workflows/terragrunt-plan-core.yml'
              - 'terragrunt/env/common/**'
              - 'terragrunt/env/terragrunt.hcl'

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::871282759583:role/ConfigTerraformAdministratorRole
          role-session-name: CBSGitHubActions
          aws-region: "ca-central-1"

      - name: Set the Terragrunt IAM role
        run: |
          echo "TERRAGRUNT_IAM_ROLE=arn:aws:iam::925306372402:role/ConfigTerraformAdminExecutionRole" >> $GITHUB_ENV
          echo "TERRAGRUNT_IAM_ASSUME_ROLE_SESSION_NAME=CBSGitHubActions" >> $GITHUB_ENV

      - name: Terragrunt plan core account
        if: ${{ steps.filter.outputs.core_account == 'true' || steps.filter.outputs.common == 'true' }}
        uses: cds-snc/terraform-plan@8be66db9c815352044405fd33120b91918bf1f2e # tag=v2.3.1
        with:
          directory: "terragrunt/env/core/core_account"
          comment-delete: "true"
          comment-title: "Core account"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"
