name: "Terragrunt apply satellite"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/terragrunt-apply-satellite.yml"
      - "satellite_accounts"
      - "terragrunt/aws/alarms/**"      
      - "terragrunt/aws/cloudtrail/**"
      - "terragrunt/aws/config/**"
      - "terragrunt/aws/satellite_bucket/**"
      - "terragrunt/env/common/**"
      - "terragrunt/env/satellite/**"
      - "terragrunt/env/terragrunt.hcl"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.1.4
  TERRAGRUNT_VERSION: 0.36.0
  TF_INPUT: false
  TF_VAR_slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_CBS }}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:

  retrieve-accounts:
    uses: cds-snc/cloud-based-sensor/.github/workflows/retrieve-accounts.yml@main

  terragrunt-apply:
    needs: retrieve-accounts
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.retrieve-accounts.outputs.matrix)}}

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec # v1.3.2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Setup Terragrunt
        run: |
          mkdir bin
          wget -O bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v$TERRAGRUNT_VERSION/terragrunt_linux_amd64
          chmod +x bin/*
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - uses: cds-snc/paths-filter@v2.10.3
        id: filter
        with:
          filters: |
            alarms:
              - 'terragrunt/aws/alarms/**'
              - 'terragrunt/env/satellite/alarms/**'          
            cloudtrail:
              - 'terragrunt/aws/cloudtrail/**'
              - 'terragrunt/env/satellite/cloudtrail/**'
            config:
              - 'terragrunt/aws/config/**'
              - 'terragrunt/env/satellite/config/**'
            satellite_bucket:
              - 'terragrunt/aws/satellite_bucket/**'
              - 'terragrunt/env/satellite/satellite_bucket/**'
            common:
              - '.github/workflows/terragrunt-apply-satellite.yml'
              - 'satellite_accounts'
              - 'terragrunt/env/common/**'
              - 'terragrunt/env/terragrunt.hcl'

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::871282759583:role/ConfigTerraformAdministratorRole
          role-session-name: CBSGitHubActions
          aws-region: 'ca-central-1'

      - name: Set the Terragrunt IAM role
        run: |
          echo "TERRAGRUNT_IAM_ROLE=arn:aws:iam::${{ matrix.account }}:role/ConfigTerraformAdminExecutionRole" >> $GITHUB_ENV
          echo "TERRAGRUNT_IAM_ASSUME_ROLE_SESSION_NAME=CBSGitHubActions" >> $GITHUB_ENV

      - name: Terragrunt apply satellite bucket
        if: ${{ steps.filter.outputs.satellite_bucket == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: "terragrunt/env/satellite/satellite_bucket"
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terragrunt apply cloudtrail
        if: ${{ steps.filter.outputs.cloudtrail == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: "terragrunt/env/satellite/cloudtrail"
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terragrunt apply config
        if: ${{ steps.filter.outputs.config == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: "terragrunt/env/satellite/config"
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terragrunt apply alarms
        if: ${{ steps.filter.outputs.alarms == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: "terragrunt/env/satellite/alarms"
        run: terragrunt apply --terragrunt-non-interactive -auto-approve        


