name: "Terragrunt apply central"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/terragrunt-apply-central.yml"
      - "satellite_accounts"
      - "terragrunt/aws/alarms/**"
      - "terragrunt/aws/central_account/**"
      - "terragrunt/env/central/**"
      - "terragrunt/env/common/**"
      - "terragrunt/env/terragrunt.hcl"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.1.4
  TERRAGRUNT_VERSION: 0.36.0
  TF_INPUT: false
  TF_VAR_cbs_principal_arn: ${{ secrets.CBS_PRINCIPAL_ARN }}
  TF_VAR_slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_CBS }}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup terraform tools
        uses: cds-snc/terraform-tools-setup@cc15ce9039f6c37c592fb9930b70466b229d2e9b # tag=v1

      - uses: cds-snc/paths-filter@b316143212d841aed668b7b29240c719d603a9b9 # v2.10.4
        id: filter
        with:
          filters: |
            alarms:
              - 'terragrunt/aws/alarms/**'
              - 'terragrunt/env/central/alarms/**'
            central_account:
              - 'terragrunt/aws/central_account/**'
              - 'terragrunt/env/central/central_account/**'
            common:
              - '.github/workflows/terragrunt-apply-central.yml'
              - 'satellite_accounts'
              - 'terragrunt/env/common/**'
              - 'terragrunt/env/terragrunt.hcl'

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::871282759583:role/ConfigTerraformAdministratorRole
          role-session-name: CBSGitHubActions
          aws-region: "ca-central-1"

      - name: Terragrunt apply central account
        if: ${{ steps.filter.outputs.central_account == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: "terragrunt/env/central/central_account"
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terragrunt apply alarms
        if: ${{ steps.filter.outputs.alarms == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: "terragrunt/env/central/alarms"
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
