name: "Terragrunt apply central"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/terragrunt-apply-central.yml"
      - "satellite_accounts"
      - "terragrunt/aws/central_account/**"
      - "terragrunt/aws/cloudtrail/**"
      - "terragrunt/env/central/**"
      - "terragrunt/env/common/**"
      - "terragrunt/env/terragrunt.hcl"

env:
  AWS_REGION: ca-central-1
  CONFTEST_VERSION: 0.27.0
  TERRAFORM_VERSION: 1.1.4
  TERRAGRUNT_VERSION: 0.36.0
  TF_VAR_cbs_principal_arn: ${{ secrets.CBS_PRINCIPAL_ARN }}
  TF_INPUT: false

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:

  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec # v1.3.2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Setup Terragrunt
        run: |
          mkdir bin
          wget -O bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v$TERRAGRUNT_VERSION/terragrunt_linux_amd64
          chmod +x bin/*
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Install Conftest
        run: |
          wget "https://github.com/open-policy-agent/conftest/releases/download/v${{ env.CONFTEST_VERSION }}/conftest_${{ env.CONFTEST_VERSION }}_Linux_x86_64.tar.gz" \
          && wget "https://github.com/open-policy-agent/conftest/releases/download/v${{ env.CONFTEST_VERSION }}/checksums.txt" \
          && grep 'Linux_x86_64.tar.gz' < checksums.txt | sha256sum --check  --status \
          && tar -zxvf "conftest_${{ env.CONFTEST_VERSION }}_Linux_x86_64.tar.gz" conftest \
          && mv conftest /usr/local/bin \
          && rm "conftest_${{ env.CONFTEST_VERSION }}_Linux_x86_64.tar.gz" checksums.txt

      - uses: cds-snc/paths-filter@v2.10.3
        id: filter
        with:
          filters: |
            central_account:
              - 'terragrunt/aws/central_account/**'
              - 'terragrunt/env/central/central_account/**'
            cloudtrail:
              - 'terragrunt/aws/cloudtrail/**'
              - 'terragrunt/env/central/cloudtrail/**'
            common:
              - '.github/workflows/terragrunt-apply-central.yml'
              - 'satellite_accounts'
              - 'terragrunt/env/common/**'
              - 'terragrunt/env/terragrunt.hcl'

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::871282759583:role/ConfigTerraformAdministratorRole
          role-session-name: CBSGitHubActions
          aws-region: 'ca-central-1'

      - name: Terragrunt apply central account
        if: ${{ steps.filter.outputs.central_account == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: "terragrunt/env/central/central_account"
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terragrunt apply cloudtrail
        if: ${{ steps.filter.outputs.cloudtrail == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: "terragrunt/env/central/cloudtrail"
        run: terragrunt apply --terragrunt-non-interactive -auto-approve