name: "Terraform security scan"

on:
  push:
    branches:
      - main
    paths:
      - "terragrunt/aws/**"
      - ".github/workflows/terraform-security-scan.yml"      
  pull_request:
    paths:
      - "terragrunt/aws/**"
      - ".github/workflows/terraform-security-scan.yml"

jobs:
  terraform-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Checkov security scan
        uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf # tag=v12.1802.0
        with:
          directory: terragrunt/aws
          framework: terraform
          output_format: cli
          soft_fail: false