name: "Terraform security scan"

on:
  push:
    branches:
      - main
    paths:
      - "terragrunt/aws/**"
      - ".github/workflows/terraform-security-scan.yml"      
  pull_request:
    paths:
      - "terragrunt/aws/**"
      - ".github/workflows/terraform-security-scan.yml"

jobs:
  terraform-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkov security scan
        uses: bridgecrewio/checkov-action@8d1675bd19257514c72879a34c5dfe108d0d3028 # latest as of Jan 19, 2022
        with:
          directory: aws
          framework: terraform
          output_format: cli
          soft_fail: false